from pydantic import BaseModel, Field
from typing import List


class Source(BaseModel):
    """Schema for a source used by the agent"""
    url: str = Field(description="URL of the source")


class AgentResponse(BaseModel):
    """Schema for the agent's response"""
    answer: str = Field(description="The answer generated by the agent")
    sources: List[Source] = Field(default_factory=list, description="List of sources used to generate the answer")
